import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'max-w-[1280px] m-auto'}>
          <p>Header</p>
          <div className="">{children}</div>
          <p>Footer</p>
        </div>
      </body>
    </html>
  );
}
